name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: 16
          cache: yarn
      - name: Yarn Install
        run: yarn install --immutable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Typescript
        run: yarn tsc --noEmit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
