name: Build Chrome Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn install
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Chrome extension
      run: yarn build:extension
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ vars.URL }}
        VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ vars.VITE_SUPABASE_ANON_KEY }}

    - name: Zip Chrome extension
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -tzip ./extension.zip dist/*

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: chrome-extension
        path: ./extension.zip
